(in-package :pulseaudio)

(include "pulse/def.h")

(ctype uint32_t "uint32_t")
(ctype int64_t "int64_t")
(ctype uint8_t "uint8_t")
(ctype size_t "size_t")

;;sys/time.h
(ctype time_t "time_t")
(ctype suseconds_t "suseconds_t")

(cstruct timeval "struct timeval"
         "UNIX time specification in seconds and microseconds."
         (tv_sec  "tv_sec"  :type time_t)
         (tv_usec "tv_usec" :type suseconds_t))

;;sample.h
(constant (PA_CHANNELS_MAX "PA_CHANNELS_MAX"))
(constant (PA_RATE_MAX "PA_RATE_MAX"))
(constant (PA_SAMPLE_U8 "PA_SAMPLE_U8"))
(constant (PA_SAMPLE_ALAW "PA_SAMPLE_ALAW"))
(constant (PA_SAMPLE_ULAW "PA_SAMPLE_ULAW"))
(constant (PA_SAMPLE_S16LE "PA_SAMPLE_S16LE"))
(constant (PA_SAMPLE_S16BE "PA_SAMPLE_S16BE"))
(constant (PA_SAMPLE_FLOAT32LE "PA_SAMPLE_FLOAT32LE"))
(constant (PA_SAMPLE_FLOAT32BE "PA_SAMPLE_FLOAT32BE"))
(constant (PA_SAMPLE_S32LE "PA_SAMPLE_S32LE"))
(constant (PA_SAMPLE_S32BE "PA_SAMPLE_S32BE"))
(constant (PA_SAMPLE_S24LE "PA_SAMPLE_S24LE"))
(constant (PA_SAMPLE_S24BE "PA_SAMPLE_S24BE"))
(constant (PA_SAMPLE_S24_32LE "PA_SAMPLE_S24_32LE"))
(constant (PA_SAMPLE_S24_32BE "PA_SAMPLE_S24_32BE"))
(constant (PA_SAMPLE_MAX "PA_SAMPLE_MAX"))
(constant (PA_SAMPLE_INVALID "PA_SAMPLE_INVALID"))

(constant (PA_SAMPLE_S16NE "PA_SAMPLE_S16NE"))
(constant (PA_SAMPLE_FLOAT32NE "PA_SAMPLE_FLOAT32NE"))
(constant (PA_SAMPLE_S32NE "PA_SAMPLE_S32NE"))
(constant (PA_SAMPLE_S24NE "PA_SAMPLE_S24NE"))
(constant (PA_SAMPLE_S24_32NE "PA_SAMPLE_S24_32NE"))
(constant (PA_SAMPLE_S16RE "PA_SAMPLE_S16RE"))
(constant (PA_SAMPLE_FLOAT32RE "PA_SAMPLE_FLOAT32RE"))
(constant (PA_SAMPLE_S32RE "PA_SAMPLE_S32RE"))
(constant (PA_SAMPLE_S24RE "PA_SAMPLE_S24RE"))
(constant (PA_SAMPLE_S24_32RE "PA_SAMPLE_S24_32RE"))
(constant (PA_SAMPLE_FLOAT32 "PA_SAMPLE_FLOAT32"))

(constant (PA_SAMPLE_U8 "PA_SAMPLE_U8"))
(constant (PA_SAMPLE_ALAW "PA_SAMPLE_ALAW"))
(constant (PA_SAMPLE_ULAW "PA_SAMPLE_ULAW"))
(constant (PA_SAMPLE_S16LE "PA_SAMPLE_S16LE"))
(constant (PA_SAMPLE_S16BE "PA_SAMPLE_S16BE"))
(constant (PA_SAMPLE_FLOAT32LE "PA_SAMPLE_FLOAT32LE"))
(constant (PA_SAMPLE_FLOAT32BE "PA_SAMPLE_FLOAT32BE"))
(constant (PA_SAMPLE_S32LE "PA_SAMPLE_S32LE"))
(constant (PA_SAMPLE_S32BE "PA_SAMPLE_S32BE"))
(constant (PA_SAMPLE_S24LE "PA_SAMPLE_S24LE"))
(constant (PA_SAMPLE_S24BE "PA_SAMPLE_S24BE"))
(constant (PA_SAMPLE_S24_32LE "PA_SAMPLE_S24_32LE"))
(constant (PA_SAMPLE_S24_32BE "PA_SAMPLE_S24_32BE"))

(ctype pa_sample_format_t "pa_sample_format_t")

(cstruct pa_sample_spec "pa_sample_spec"
         "A sample format and attribute specification."
         (pa_sample_spec-format "format"  :type pa_sample_format_t)
         (pa_sample_spec-rate "rate"  :type uint32_t)
         (pa_sample_spec-channels "channels"  :type uint8_t))

(ctype pa_usec_t "pa_usec_t")

(constant (PA_SAMPLE_SPEC_SNPRINT_MAX "PA_SAMPLE_SPEC_SNPRINT_MAX"))
(constant (PA_BYTES_SNPRINT_MAX "PA_BYTES_SNPRINT_MAX"))

;;defs.h

(constant (PA_CONTEXT_UNCONNECTED "PA_CONTEXT_UNCONNECTED"))
(constant (PA_CONTEXT_CONNECTING "PA_CONTEXT_CONNECTING"))
(constant (PA_CONTEXT_AUTHORIZING "PA_CONTEXT_AUTHORIZING"))
(constant (PA_CONTEXT_SETTING_NAME "PA_CONTEXT_SETTING_NAME"))
(constant (PA_CONTEXT_READY "PA_CONTEXT_READY"))
(constant (PA_CONTEXT_FAILED "PA_CONTEXT_FAILED"))
(constant (PA_CONTEXT_TERMINATED "PA_CONTEXT_TERMINATED"))

(constant (PA_STREAM_UNCONNECTED "PA_STREAM_UNCONNECTED"))
(constant (PA_STREAM_CREATING "PA_STREAM_CREATING"))
(constant (PA_STREAM_READY "PA_STREAM_READY"))
(constant (PA_STREAM_FAILED "PA_STREAM_FAILED"))
(constant (PA_STREAM_TERMINATED "PA_STREAM_TERMINATED"))

(constant (PA_OPERATION_RUNNING "PA_OPERATION_RUNNING"))
(constant (PA_OPERATION_DONE "PA_OPERATION_DONE"))
(constant (PA_OPERATION_CANCELLED "PA_OPERATION_CANCELLED"))

(constant (PA_INVALID_INDEX "PA_INVALID_INDEX"))

(constant (PA_CONTEXT_NOFLAGS "PA_CONTEXT_NOFLAGS"))
(constant (PA_CONTEXT_NOAUTOSPAWN "PA_CONTEXT_NOAUTOSPAWN"))
(constant (PA_CONTEXT_NOFAIL "PA_CONTEXT_NOFAIL"))

(constant (PA_DIRECTION_OUTPUT "PA_DIRECTION_OUTPUT"))
(constant (PA_DIRECTION_INPUT "PA_DIRECTION_INPUT"))

(constant (PA_DEVICE_TYPE_SINK "PA_DEVICE_TYPE_SINK"))
(constant (PA_DEVICE_TYPE_SOURCE "PA_DEVICE_TYPE_SOURCE"))

(constant (PA_STREAM_NODIRECTION "PA_STREAM_NODIRECTION"))
(constant (PA_STREAM_PLAYBACK "PA_STREAM_PLAYBACK"))
(constant (PA_STREAM_RECORD "PA_STREAM_RECORD"))
(constant (PA_STREAM_UPLOAD "PA_STREAM_UPLOAD"))
(ctype pa_stream_direction_t "pa_stream_direction_t")

(constant (PA_STREAM_NOFLAGS "PA_STREAM_NOFLAGS"))
(constant (PA_STREAM_START_CORKED "PA_STREAM_START_CORKED"))
(constant (PA_STREAM_INTERPOLATE_TIMING "PA_STREAM_INTERPOLATE_TIMING"))
(constant (PA_STREAM_NOT_MONOTONIC "PA_STREAM_NOT_MONOTONIC"))
(constant (PA_STREAM_AUTO_TIMING_UPDATE "PA_STREAM_AUTO_TIMING_UPDATE"))
(constant (PA_STREAM_NO_REMAP_CHANNELS "PA_STREAM_NO_REMAP_CHANNELS"))
(constant (PA_STREAM_NO_REMIX_CHANNELS "PA_STREAM_NO_REMIX_CHANNELS"))
(constant (PA_STREAM_FIX_FORMAT "PA_STREAM_FIX_FORMAT"))
(constant (PA_STREAM_FIX_RATE "PA_STREAM_FIX_RATE"))
(constant (PA_STREAM_FIX_CHANNELS "PA_STREAM_FIX_CHANNELS"))
(constant (PA_STREAM_DONT_MOVE "PA_STREAM_DONT_MOVE"))
(constant (PA_STREAM_VARIABLE_RATE "PA_STREAM_VARIABLE_RATE"))
(constant (PA_STREAM_PEAK_DETECT "PA_STREAM_PEAK_DETECT"))
(constant (PA_STREAM_START_MUTED "PA_STREAM_START_MUTED"))
(constant (PA_STREAM_ADJUST_LATENCY "PA_STREAM_ADJUST_LATENCY"))
(constant (PA_STREAM_EARLY_REQUESTS "PA_STREAM_EARLY_REQUESTS"))
(constant (PA_STREAM_DONT_INHIBIT_AUTO_SUSPEND "PA_STREAM_DONT_INHIBIT_AUTO_SUSPEND"))
(constant (PA_STREAM_START_UNMUTED "PA_STREAM_START_UNMUTED"))
(constant (PA_STREAM_FAIL_ON_SUSPEND "PA_STREAM_FAIL_ON_SUSPEND"))
(constant (PA_STREAM_RELATIVE_VOLUME "PA_STREAM_RELATIVE_VOLUME"))
(constant (PA_STREAM_PASSTHROUGH "PA_STREAM_PASSTHROUGH"))

(cstruct pa_buffer_attr "pa_buffer_attr"
         "Playback and record buffer metrics"
         (pa_buffer_attr-maxlength "maxlength"  :type uint32_t)
         (pa_buffer_attr-rate "tlength"  :type uint32_t)
         (pa_buffer_attr-prebuf "prebuf" :type uint32_t)
         (pa_buffer_attr-minreq "minreq" :type uint32_t)
         (pa_buffer_attr-fragsize "fragsize" :type uint32_t))

(constant (PA_OK "PA_OK"))
(constant (PA_ERR_ACCESS "PA_ERR_ACCESS"))
(constant (PA_ERR_COMMAND "PA_ERR_COMMAND"))
(constant (PA_ERR_INVALID "PA_ERR_INVALID"))
(constant (PA_ERR_EXIST "PA_ERR_EXIST"))
(constant (PA_ERR_NOENTITY "PA_ERR_NOENTITY"))
(constant (PA_ERR_CONNECTIONREFUSED "PA_ERR_CONNECTIONREFUSED"))
(constant (PA_ERR_PROTOCOL "PA_ERR_PROTOCOL"))
(constant (PA_ERR_TIMEOUT "PA_ERR_TIMEOUT"))
(constant (PA_ERR_AUTHKEY "PA_ERR_AUTHKEY"))
(constant (PA_ERR_INTERNAL "PA_ERR_INTERNAL"))
(constant (PA_ERR_CONNECTIONTERMINATED "PA_ERR_CONNECTIONTERMINATED"))
(constant (PA_ERR_KILLED "PA_ERR_KILLED"))
(constant (PA_ERR_INVALIDSERVER "PA_ERR_INVALIDSERVER"))
(constant (PA_ERR_MODINITFAILED "PA_ERR_MODINITFAILED"))
(constant (PA_ERR_BADSTATE "PA_ERR_BADSTATE"))
(constant (PA_ERR_NODATA "PA_ERR_NODATA"))
(constant (PA_ERR_VERSION "PA_ERR_VERSION"))
(constant (PA_ERR_TOOLARGE "PA_ERR_TOOLARGE"))
(constant (PA_ERR_NOTSUPPORTED "PA_ERR_NOTSUPPORTED"))
(constant (PA_ERR_UNKNOWN "PA_ERR_UNKNOWN"))
(constant (PA_ERR_NOEXTENSION "PA_ERR_NOEXTENSION"))
(constant (PA_ERR_OBSOLETE "PA_ERR_OBSOLETE"))
(constant (PA_ERR_NOTIMPLEMENTED "PA_ERR_NOTIMPLEMENTED"))
(constant (PA_ERR_FORKED "PA_ERR_FORKED"))
(constant (PA_ERR_IO "PA_ERR_IO"))
(constant (PA_ERR_BUSY "PA_ERR_BUSY"))
(constant (PA_ERR_MAX "PA_ERR_MAX"))

(constant (PA_SUBSCRIPTION_MASK_NULL "PA_SUBSCRIPTION_MASK_NULL"))
(constant (PA_SUBSCRIPTION_MASK_SINK "PA_SUBSCRIPTION_MASK_SINK"))
(constant (PA_SUBSCRIPTION_MASK_SOURCE "PA_SUBSCRIPTION_MASK_SOURCE"))
(constant (PA_SUBSCRIPTION_MASK_SINK_INPUT "PA_SUBSCRIPTION_MASK_SINK_INPUT"))
(constant (PA_SUBSCRIPTION_MASK_SOURCE_OUTPUT "PA_SUBSCRIPTION_MASK_SOURCE_OUTPUT"))
(constant (PA_SUBSCRIPTION_MASK_MODULE "PA_SUBSCRIPTION_MASK_MODULE"))
(constant (PA_SUBSCRIPTION_MASK_CLIENT "PA_SUBSCRIPTION_MASK_CLIENT"))
(constant (PA_SUBSCRIPTION_MASK_SAMPLE_CACHE "PA_SUBSCRIPTION_MASK_SAMPLE_CACHE"))
(constant (PA_SUBSCRIPTION_MASK_SERVER "PA_SUBSCRIPTION_MASK_SERVER"))
(constant (PA_SUBSCRIPTION_MASK_AUTOLOAD "PA_SUBSCRIPTION_MASK_AUTOLOAD"))
(constant (PA_SUBSCRIPTION_MASK_CARD "PA_SUBSCRIPTION_MASK_CARD"))
(constant (PA_SUBSCRIPTION_MASK_ALL "PA_SUBSCRIPTION_MASK_ALL"))

(constant (PA_SUBSCRIPTION_EVENT_SINK "PA_SUBSCRIPTION_EVENT_SINK"))
(constant (PA_SUBSCRIPTION_EVENT_SOURCE "PA_SUBSCRIPTION_EVENT_SOURCE"))
(constant (PA_SUBSCRIPTION_EVENT_SINK_INPUT "PA_SUBSCRIPTION_EVENT_SINK_INPUT"))
(constant (PA_SUBSCRIPTION_EVENT_SOURCE_OUTPUT "PA_SUBSCRIPTION_EVENT_SOURCE_OUTPUT"))
(constant (PA_SUBSCRIPTION_EVENT_MODULE "PA_SUBSCRIPTION_EVENT_MODULE"))
(constant (PA_SUBSCRIPTION_EVENT_CLIENT "PA_SUBSCRIPTION_EVENT_CLIENT"))
(constant (PA_SUBSCRIPTION_EVENT_SAMPLE_CACHE "PA_SUBSCRIPTION_EVENT_SAMPLE_CACHE"))
(constant (PA_SUBSCRIPTION_EVENT_SERVER "PA_SUBSCRIPTION_EVENT_SERVER"))
(constant (PA_SUBSCRIPTION_EVENT_AUTOLOAD "PA_SUBSCRIPTION_EVENT_AUTOLOAD"))
(constant (PA_SUBSCRIPTION_EVENT_CARD "PA_SUBSCRIPTION_EVENT_CARD"))
(constant (PA_SUBSCRIPTION_EVENT_FACILITY_MASK "PA_SUBSCRIPTION_EVENT_FACILITY_MASK"))
(constant (PA_SUBSCRIPTION_EVENT_NEW "PA_SUBSCRIPTION_EVENT_NEW"))
(constant (PA_SUBSCRIPTION_EVENT_CHANGE "PA_SUBSCRIPTION_EVENT_CHANGE"))
(constant (PA_SUBSCRIPTION_EVENT_REMOVE "PA_SUBSCRIPTION_EVENT_REMOVE"))
(constant (PA_SUBSCRIPTION_EVENT_TYPE_MASK "PA_SUBSCRIPTION_EVENT_TYPE_MASK"))

(cstruct pa_timing_info "pa_timing_info"
         "A structure for all kinds of timing information of a stream"
         (pa_timing_info-timestamp "timestamp" :type timeval)
         (pa_timing_info-synchronized_clocks "synchronized_clocks" :type :int)
         (pa_timing_info-sink_usec "sink_usec" :type pa_usec_t)
         (pa_timing_info-source_usec "source_usec" :type pa_usec_t)
         (pa_timing_info-transport_usec "transport_usec" :type pa_usec_t)
         (pa_timing_info-playing "playing" :type :int)
         (pa_timing_info-write_index_corrupt "write_index_corrupt" :type :int)
         (pa_timing_info-write_index "write_index" :type int64_t)
         (pa_timing_info-read_index_corrupt "read_index_corrupt" :type :int)
         (pa_timing_info-read_index "read_index" :type  int64_t)
         (pa_timing_info-configured_sink_usec "configured_sink_usec" :type pa_usec_t)
         (pa_timing_info-configured_source_usec "configured_source_usec" :type pa_usec_t)
         (pa_timing_info-since_underrun "since_underrun" :type int64_t))

(cstruct pa_spawn_api "pa_spawn_api"
         "A structure for the spawn api"
         (pa_spawn_api-prefork  "prefork" :type :pointer)
         (pa_spawn_api-postfork "postfork" :type :pointer)
         (pa_spawn_api-atfork   "atfork" :type :pointer))

(constant (PA_SEEK_RELATIVE "PA_SEEK_RELATIVE"))
(constant (PA_SEEK_ABSOLUTE "PA_SEEK_ABSOLUTE"))
(constant (PA_SEEK_RELATIVE_ON_READ "PA_SEEK_RELATIVE_ON_READ"))
(constant (PA_SEEK_RELATIVE_END "PA_SEEK_RELATIVE_END"))

(constant (PA_SINK_NOFLAGS "PA_SINK_NOFLAGS"))
(constant (PA_SINK_HW_VOLUME_CTRL "PA_SINK_HW_VOLUME_CTRL"))
(constant (PA_SINK_LATENCY "PA_SINK_LATENCY"))
(constant (PA_SINK_HARDWARE "PA_SINK_HARDWARE"))
(constant (PA_SINK_NETWORK "PA_SINK_NETWORK"))
(constant (PA_SINK_HW_MUTE_CTRL "PA_SINK_HW_MUTE_CTRL"))
(constant (PA_SINK_DECIBEL_VOLUME "PA_SINK_DECIBEL_VOLUME"))
(constant (PA_SINK_FLAT_VOLUME "PA_SINK_FLAT_VOLUME"))
(constant (PA_SINK_DYNAMIC_LATENCY "PA_SINK_DYNAMIC_LATENCY"))
(constant (PA_SINK_SET_FORMATS "PA_SINK_SET_FORMATS"))

(constant (PA_SINK_INVALID_STATE "PA_SINK_INVALID_STATE"))
(constant (PA_SINK_IDLE "PA_SINK_IDLE"))
(constant (PA_SINK_SUSPENDED "PA_SINK_SUSPENDED"))
(constant (PA_SINK_INIT "PA_SINK_INIT"))
(constant (PA_SINK_UNLINKED "PA_SINK_UNLINKED"))

(constant (PA_SOURCE_NOFLAGS "PA_SOURCE_NOFLAGS"))
(constant (PA_SOURCE_HW_VOLUME_CTRL "PA_SOURCE_HW_VOLUME_CTRL"))
(constant (PA_SOURCE_LATENCY "PA_SOURCE_LATENCY"))
(constant (PA_SOURCE_HARDWARE "PA_SOURCE_HARDWARE"))
(constant (PA_SOURCE_NETWORK "PA_SOURCE_NETWORK"))
(constant (PA_SOURCE_HW_MUTE_CTRL "PA_SOURCE_HW_MUTE_CTRL"))
(constant (PA_SOURCE_DECIBEL_VOLUME "PA_SOURCE_DECIBEL_VOLUME"))
(constant (PA_SOURCE_DYNAMIC_LATENCY "PA_SOURCE_DYNAMIC_LATENCY"))
(constant (PA_SOURCE_FLAT_VOLUME "PA_SOURCE_FLAT_VOLUME"))
(constant (PA_SOURCE_CLIENT_FLAGS_MASK "PA_SOURCE_CLIENT_FLAGS_MASK"))

(constant (PA_SOURCE_INVALID_STATE "PA_SOURCE_INVALID_STATE"))
(constant (PA_SOURCE_RUNNING "PA_SOURCE_RUNNING"))
(constant (PA_SOURCE_IDLE "PA_SOURCE_IDLE"))
(constant (PA_SOURCE_SUSPENDED "PA_SOURCE_SUSPENDED"))
(constant (PA_SOURCE_INIT "PA_SOURCE_INIT"))
(constant (PA_SOURCE_UNLINKED "PA_SOURCE_UNLINKED"))

;;(constant (PA_STREAM_EVENT_REQUEST_CORK "PA_STREAM_EVENT_REQUEST_CORK")) "request-cork"
;;(constant (PA_STREAM_EVENT_REQUEST_UNCORK "PA_STREAM_EVENT_REQUEST_UNCORK")) "request-uncork"
;;(constant (PA_STREAM_EVENT_FORMAT_LOST "PA_STREAM_EVENT_FORMAT_LOST")) "format-lost"

(constant (PA_PORT_AVAILABLE_UNKNOWN "PA_PORT_AVAILABLE_UNKNOWN"))
(constant (PA_PORT_AVAILABLE_NO "PA_PORT_AVAILABLE_NO"))
(constant (PA_PORT_AVAILABLE_YES "PA_PORT_AVAILABLE_YES"))
